### ISSUE TITLE
async belongsTo stops working when there is hasMany on parent model

### ISSUE THREAD

**Issue by MartinMalinda** [firebase/emberfire#300]
EmberFire: v1.50, Ember Data: 1.13.5
So I have this on my model A: ```user:  DS.belongsTo('user', {async: true})```
Everything works just as I need, user gets loaded asynchronously when I request it, but it all suddenly stops working when I put ```projects: DS.hasMany('project', {async: true})``` on model B.

Ember inspector shows the user has indeed been loaded in Ember data, yet the relationship does not work somehow. Getter function returns undefined.

**Comment by MartinMalinda** [comment]
Had to do this to overcome the issue:
```javascript
var userId = model.get('user.id'); // user.id is fetchable, yet user.email is not

		this.store.find('user', userId).then(function(user){
			model.set('user', user);
		});
```

**Comment by MartinMalinda** [comment]
Might be because of using Ember 2.0?

**Comment by tstirrat** [comment]
Thanks for the report on this.

I just had another report of the same issue and it's happening in 1.13.x too.

There is some kind of race condition in the way ember 1.13+ does relationships.

**Comment by MartinMalinda** [comment]
D'oh. I just fixed this issue and it's totally my miskake. User has not been saving properly after adding a project. Had to do save() on `session.user.content` instead of `session.user`. My bad.

**Comment by halfdan** [comment]
@MartinMalinda this is still happening for a project I'm working on. It's interesting that this fixed it for you - for me the behaviour is still showing when just fetching the parent and then accessing the hasMany elements.

**Comment by halfdan** [comment]
@tstirrat @sararob Any chance of getting this fixed / anywhere I can help?

**Comment by tstirrat** [comment]
@halfdan I've had a busy week, but should get a chance to look at this again tomorrow

**Comment by tstirrat** [comment]
Hey all, I'm unable to repro this issue in a [MCVE](http://stackoverflow.com/help/mcve).

Can anyone help update [this repo](https://github.com/tstirrat/emberfire-issue-300) so we can consistently produce this issue?

**Comment by tstirrat** [comment]
I think this is related to emberjs/data#3614

I think it is a problem when you add the `hasMany ` definition later, after you already created the user and project.

The `project.user` relationship is fine. but when you add the inverse `hasMany`, now the serializer is finding the user.. and then it looks at the `user.projects` relationship, this is empty on the server, and the serializer gets two sets of conflicting information.. this causes it to wipeout the relationship...

I'm still trying to find a simple reproduction for it.

**Comment by tstirrat** [comment]
Looks like I found a minimal reproduction: https://github.com/tstirrat/emberfire-issue-300

**Comment by tstirrat** [comment]
So, to sum this issue up.

Ember Data became more strict in the way it handles relationships. With the new serializer API, if you have two sets of conflicting information in your relationships, the relationship information loaded **last** will win. (emberjs/data#3614)

If you define a model with `project has one user` this will be fine. If you decide to define the reflexive relationship of `user has many projects` *at a later date* you will get broken relationships when the user model loads. All those users that you already saved without the reflexive project links will now load with relationship information that says "I have zero projects".

Your solution could be:

- remove the reflexive relationship if you don't need it. **OR**

- manually migrate your existing data

    ```js 
    // DISCLAIMER: this code is an example only, 
    // review it and use it at your own risk!
    var ref = new Firebase('https://some-app-name.firebaseio.com');

    ref.child('projects').once('value', function(projects) {
      projects.forEach(function(snapshot) {
        var project = snapshot.val();
        project.id = snapshot.key();
    
        if (project.user) {
          var projectLink = ref.child('users/' + project.user + '/projects/' + project.id);
          projectLink.once('value', function(linkSnap) {
            if (!linkSnap.val()) {
              // log all the changes that need to happen
              console.log('User ' + project.user + ' should have link to project ' + project.id);
              // projectLink.set(true); // uncomment here if you want to actually write the changes
            }
          })
        }
      });
    });
    ```

**Comment by tstirrat** [comment]
Closing this because there is not much we can do about it. Please re-open with a minimal test if you think there is another aspect of this issue that I haven't covered here.
